[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88
target-version = "py38"
extend-exclude = [
    "nnsvs/usfgan/layers",
    "nnsvs/usfgan/models",
    "nnsvs/usfgan/utils",
]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B"]

[tool.ruff.format]
